# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin settings
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.r8.optimizedResourceShrinking=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Kotlin Native Cache settings for simulator tests (commented out to enable native compiler cache)
# kotlin.native.cacheKind.iosSimulatorArm64=none
# kotlin.native.cacheKind.iosX64=none
