package com.payslipmax.pdfparser.ui

import com.payslipmax.pdfparser.domain.*
import com.payslipmax.pdfparser.insights.OptimizationResult

data class PayslipUiState(
    val payslips: List<ParsedPayslip> = emptyList(),
    val selectedPayslip: ParsedPayslip? = null,
    val taxOptimizationResult: OptimizationResult? = null,
    val isLoading: Boolean = true,
    val error: String? = null,
    val importError: String? = null,
    val importSuccess: Boolean = false,
    val importUiState: ImportUiState = ImportUiState.Idle,
    val isPremiumEnabled: Boolean = false,
    val appTheme: String = "system",
    val isLockEnabled: Boolean = false,
    val appPinHash: String = "",
    val profileName: String = "",
    val profileCdaNumber: String = "",
    val profilePanNumber: String = "",
    val isAppLocked: Boolean = false,
    val useLocalAi: Boolean = false,
    val isTelemetryEnabled: Boolean = true,
    val isGemmaSupported: Boolean = true,
    val gemmaSupportReason: String? = null,
    val isDownloadingModel: Boolean = false,
    val isWaitingForWifi: Boolean = false,
    val modelDownloadProgress: Float = 0f,
    val modelDownloadError: String? = null,
    val expandedHistoryYears: Set<Int> = emptySet(),
    val lastKnownHistoryYear: Int? = null,
    val historyScrollIndex: Int = 0,
    val historyScrollOffset: Int = 0,
    val insightsScrollIndex: Int = 0,
    val insightsScrollOffset: Int = 0,
    val dashboardScrollValue: Int = 0,
    val settingsScrollValue: Int = 0,
    val isEditModeActive: Boolean = false,
    val draftCorrections: Map<String, SingleCorrection> = emptyMap(),
    val historyDetailPayslipId: String? = null,
    val appIntegrityStatus: AppIntegrityStatus = AppIntegrityStatus.Valid,
)
