package com.payslipmax.pdfparser.ui.theme

import com.payslipmax.pdfparser.platform.platformAppVersion

object AppStrings {
    const val navigationHome = "Dashboard"
    const val navigationHistory = "History"
    const val navigationInsights = "Insights"
    const val navigationSettings = "Settings"
    val appVersion: String
        get() = "PayslipMax - Version ${platformAppVersion()}"

    // Statistics Cards
    const val cardNetTitle = "Latest Net Remittance"
    const val cardNetUnit = "INR (₹)"
    const val cardBpTitle = "Basic Pay (BPAY)"
    const val cardBpDesc = "+ Allowances & Arrears"
    const val cardDsopTitle = "DSOP Closing Balance"
    const val cardDsopDesc = "Provident Fund Wealth"
    const val cardTaxTitle = "Effective Tax Rate"
    const val cardTaxDesc = "Average Annual TDS"

    const val chartIncomeTitle = "Monthly Payout Trend"
    const val chartShareTitle = "Earnings Allocation"

    // Explorer
    const val explorerHeader = "Payslip Digital Replica"
    const val explorerSubheader = "Tap any transaction code for detailed explanations"
    const val replicaEarningTitle = "Earnings (₹)"
    const val replicaDeductionTitle = "Deductions (₹)"
    const val replicaNetLabel = "Net Remittance (Take Home)"
    const val replicaFooter = "Principal Controller of Defence Accounts (Officers), Pune\nMinistry of Defence, Government of India"
    const val ledgerGrossPay = "Gross Pay (Credits)"
    const val ledgerTotalDeductions = "Total Deductions (Debits)"

    // Replica metadata & glossary
    const val replicaOfficerPrefix = "Officer: "
    const val replicaCdaPrefix = "CDA A/C: "
    const val replicaPanPrefix = "PAN: "
    const val glossaryUnderstood = "Understood"

    // Confidence-gated correction (Phase 5)
    const val correctionIndicatorDesc = "Low confidence — tap to review and correct this value"
    const val correctionDialogTitle = "Correct value"
    const val correctionDialogHint = "This value was parsed with low confidence. Enter the correct amount from your payslip."
    const val correctionInvalidAmount = "Enter a valid amount"
    const val correctionSave = "Save"
    const val correctionCancel = "Cancel"
    const val correctionAiSourceBadge = "AI"
    const val correctionReasonsHeading = "This payslip needs review because:"
    const val correctionDiagnosticHintHeading = "AI flagged this field as possibly mis-extracted:"

    // Upload & Decrypt
    const val uploadHeader = "Import Encrypted Payslip"
    const val uploadDesc = "Secure, 100% offline-first parsing engine"
    const val labelSelectPdf = "Select PDF Payslip"
    const val labelPassword = "Decryption Password"
    const val showPasswordToggle = "Show"
    const val hidePasswordToggle = "Hide"
    const val loaderDecrypt = "Decrypting PDF using Secure Enclave..."
    const val uploadDismiss = "Dismiss"
    const val uploadSuccess = "Payslip Imported Successfully!"

    // Pre-Flight Validation Errors
    const val errorUnrecognizedPdf = "Unrecognised PDF. Please upload soft copy of PCDAO Payslip in PDF Format"
    const val errorEncryptedPdfTitle = "Password-Protected PDF"
    const val errorEncryptedPdfDesc = "This PDF requires a password to open. Please unlock the file before importing or use Edit Mode to enter data."
    const val errorZeroTokensTitle = "Scanned / Empty PDF"
    const val errorZeroTokensDesc = "No readable text was found in this PDF. It may be a scanned image or photo. You can enter details manually via Edit Mode."
    const val errorUnrecognizedFormatTitle = "Unrecognized Format"
    const val errorUnrecognizedFormatDesc = "This document does not match a PCDA(O) payslip layout. You can still use Edit Mode to manually add your figures."

    // Dashboard - Officer Info Bar
    const val cdaInfoLabel = "CDA A/C"
    const val panInfoLabel = "PAN"

    // Dashboard - Year/Month Picker
    const val selectYearLabel = "Year"
    const val selectMonthLabel = "Month"
    const val analyzingStatement = "Analyze Payslip"

    // Security Lock Screen
    const val lockScreenTitle = "Secured Portal"
    const val lockScreenSubtitle = "Enter your 4-digit PIN to decrypt your dashboard"
    const val lockScreenError = "Incorrect PIN, please try again"
    const val lockScreenForgotPin = "Forgot PIN?"
    const val lockScreenResetDialogTitle = "Reset Passcode"
    const val lockScreenResetDialogDesc = "Please select a valid statement PDF and enter its decryption password to verify ownership."
    const val lockScreenResetErrorMismatch = "PDF does not match the active user profile."
    const val lockScreenResetConfirmBtn = "Verify & Reset"

    // Settings Interface
    const val settingsAccountSubscriptionHeader = "Account & Subscription"
    const val settingsSecurityPrivacyHeader = "Security & Privacy"
    const val settingsTelemetryLabel = "Anonymous Telemetry"
    const val settingsTelemetryDesc = "Share anonymous model installation state to help us improve the app"
    const val settingsThemeLabel = "App Appearance"
    const val settingsThemeLight = "Light Mode"
    const val settingsThemeDark = "Dark Mode"
    const val settingsThemeSystem = "System Default"
    const val settingsProfileHeader = "Officer Profile & Salary Settings"
    const val settingsProfileDesc = "Set default identity details for dashboard, reports & security verification."
    const val settingsProfileRowSubtitleUnconfigured = "Set name, CDA & PAN to personalize dashboard & reports"
    const val settingsProfileInfoBannerHeader = "What does entering these details do?"
    const val settingsProfileInfoBannerBullet1 = "• Personalizes your Dashboard header, digital replicas, and AI insights."
    const val settingsProfileInfoBannerBullet2 = "• Overrides missing or unreadable identity fields from parsed PDFs."
    const val settingsProfileInfoBannerBullet3 = "• Acts as account verification for passcode resets & backup restores."
    const val settingsProfileName = "Officer Name"
    const val settingsProfileCda = "CDA Account Number"
    const val settingsProfilePan = "PAN Number"
    const val settingsPremiumPlanTitle = "Advanced Tax & Financial Insights"
    const val premiumTeaserCrownIcon = "👑"
    const val premiumLockIcon = "🔒"
    const val aiRegenerateIcon = "🔄"
    const val settingsPremiumPlanDesc = "Unlock personalization & CA-grade tax advice"

    // Static fallback shown until PayslipViewModel.premiumPriceState resolves the live store price.
    const val settingsPremiumPlanPrice = "₹199 / Year"
    const val settingsPremiumPlanBillingNote = "Yearly Auto-Renewing Subscription"
    const val settingsPremiumPlanActive = "Premium Plan Activated"
    const val settingsPremiumPlanUpgradeTitle = "Upgrade to PayslipMax Premium"
    const val settingsPremiumPlanSubscribedNote = "Subscribed (Auto-Renewing Subscription Active)"

    // Composed with the live/fallback price at the call site, e.g. "$settingsPremiumPlanUpgradeSubtitlePrefix (₹199 / Year)".
    const val settingsPremiumPlanUpgradeSubtitlePrefix = "Unlock Advanced Insights & Cloud Backup"
    const val settingsRestorePurchasesTitle = "Restore Purchases"
    const val settingsRestorePurchasesSubtitle = "Recover your Premium subscription on this device"
    const val statusRestorePurchasesSuccess = "Purchases restored"
    const val statusRestorePurchasesFailed = "Restore failed: "
    const val statusPurchaseSuccess = "Premium activated!"
    const val statusPurchaseFailed = "Purchase failed: "

    const val settingsTermsOfUse = "Terms of Use"
    const val legalSeparator = " · "
    const val settingsDeleteAll = "Reset App & Clear Data"
    const val settingsDeleteConfirm = "Are you sure you want to wipe all local database records? This action is permanent."
    const val settingsDangerZoneDesc = "Wipe all local database statements, cached PDFs, and passcode configuration."
    const val settingsDeleteConfirmTitle = "Wipe App Data?"
    const val settingsDeleteConfirmBtn = "Delete Everything"
    const val btnCancel = "Cancel"
    const val btnBack = "Back"
    const val settingsSetPasscodeTitle = "Set 4-Digit Passcode"
    const val settingsSetPasscodeLabel = "Enter 4-Digit PIN"
    const val settingsSetPasscodeConfirmBtn = "Enable Lock"
    const val settingsProfileSaveBtn = "Save Adjustments"
    const val settingsBackupHeader = "Backup & Restore"
    const val settingsBackupDesc = "Backup is locally AES-256 encrypted using your password. Save the file anywhere (Drive, iCloud, email) and restore it on any phone."
    const val pdfCardTapHint = "Tap to open original statement"
    const val pdfCardBadge = "PDF"
    const val pdfCardOpenCdesc = "Open"
    const val settingsBackupSaveBtn = "Back Up"
    const val settingsBackupRestoreBtn = "Restore"
    const val settingsBackupPasswordRequired = "Enter a password to protect your backup."
    const val settingsStatusBackupPremium = "Restore free · Backup is PREMIUM"
    const val settingsRestoreExistingTitle = "Payslips already on this device"
    const val settingsRestoreExistingMsg = "Replace them with the backup, or merge both together?"
    const val settingsRestoreReplaceBtn = "Replace all"
    const val settingsRestoreMergeBtn = "Merge"
    const val statusRestoreFailed = "Restore Failed: "
    const val statusRestoreComplete = "Restore Complete!"
    const val statusBackupFailed = "Backup Failed: "
    const val labelPayslipsBackedUp = "payslips backed up"
    const val statusNoPayslipsToBackup = "No payslips to back up yet."
    const val settingsDataManagementHeader = "Data Management"
    const val settingsSecurityEncryptionStatusLabel = "Local Encryption Status"
    const val settingsSecurityEncryptionStatusSubtitle = "100% Offline & Encrypted"
    const val premiumBadgeTag = "PREMIUM"
    const val settingsSubtitle = "Manage your profile, security, and data backups"
    const val settingsOfflineFirst = "Offline-First"
    const val settingsOfflineSecureTitle = "100% Offline & Secure"
    const val settingsOfflineSecureDesc = "All payslip decryption and parsing happens locally on your device. Your data never leaves your control."
    const val settingsAiPoweredByProxy = "AI insights powered by on-device Gemma"
    const val settingsDevOverrideTitle = "Developer · Premium Override"
    const val settingsDevOverrideDesc = "Debug-only entitlement override. Not present in release builds."
    const val settingsDevOverrideFollowFlag = "Follow Flag"
    const val settingsDevOverrideForcePremium = "Force Premium"
    const val settingsDevOverrideForceFree = "Force Free"
    const val settingsStagingTitle = "Staging & Testing Sandbox"
    const val settingsStagingDesc = "Load simulated Army Officer records (2022-2025) to evaluate the analytical tools immediately."
    const val settingsStagingSeedBtn = "Seed Staging Data"
    const val settingsStagingClearBtn = "Clear All"
    const val settingsStagingCrashTestBtn = "Crash Test (Crashlytics)"
    const val settingsHelpDocsHeader = "Help & Legal"
    const val settingsHelpFaqTitle = "Frequently Asked Questions (FAQ)"
    const val settingsHelpPrivacyTitle = "Privacy Policy"
    const val settingsHelpAiTitle = "AI Privacy Promise"
    const val settingsHelpDisclaimerTitle = "Legal Disclaimer"

    // Redesign & Premium Tier
    const val settingsPremiumPlanBullet1 = "• CA-Grade Financial Audits & Advice"
    const val settingsPremiumPlanBullet2 = "• Personalized Tax Saving Insights"
    const val settingsPremiumPlanBullet3 = "• Secure Local & Cross-Platform Backups"
    const val settingsPremiumPlanBullet4 = "• 100% Offline & Private Processing"
    const val settingsPremiumUpgradeBtn = "Unlock Premium Tier"
    const val settingsRowThemeLabel = "App Appearance"
    const val settingsRowPasscodeLabel = "App Passcode Lock"
    const val settingsRowBackupLabel = "Backup & Restore"
    const val settingsRowProfileLabel = "Officer Profile & Salary Settings"
    const val settingsStatusNotConfigured = "Not Configured"
    const val settingsStatusConfigured = "Configured"
    const val settingsStatusEnabled = "Enabled"
    const val settingsStatusDisabled = "Disabled"

    // Re-parse All Payslips
    const val settingsRowReparseLabel = "Re-parse All Payslips"
    const val settingsReparseSubtitle = "Fix payslips parsed before an app update"
    const val settingsReparseDialogTitle = "Re-parse All Payslips"
    const val settingsReparseDialogBody = "Re-runs every saved payslip through the current parser and replaces its stored result. Your saved corrections are kept. Enter your payslip PDF password to continue."
    const val settingsReparsePasswordLabel = "Payslip PDF Password"
    const val settingsReparseConfirmBtn = "Re-parse All"
    const val settingsReparseSuccessPrefix = "Re-parsed "
    const val settingsReparseFailedSuffix = "Could not re-parse: "
    const val settingsReparseErrorPrefix = "Re-parse failed: "

    // History Redesign Strings
    const val historyActionDelete = "Delete Statement"
    const val historyConfirmDeleteTitle = "Delete Payslip?"
    const val historyConfirmDeleteMessage = "Are you sure you want to delete this payslip? This action is permanent and cannot be undone."
    const val historyHeaderDescription = "Browse and read your historical military payslip statements"
    const val historyEmptyState = "No payslips in history. Go to Dashboard to import one."
    const val historyActionViewReplica = "View Digital Replica"
    const val historyActionViewOriginal = "View Original PDF"
    const val historyActionShareSummary = "Share Summary"
    const val historyNetTakeHomeLabel = "Net Take-Home"
    const val historyGrossPayLabel = "Gross"
    const val historyDsopLabel = "DSOP"
    const val historyTaxLabel = "Tax"
    const val historyChevronContentDescription = "Toggle Year Visibility"
    const val historyLedgerTitle = "Historical Ledger Table"
    const val historyLedgerHeaderMonth = "Month"
    const val historyLedgerHeaderBasic = "Basic"
    const val historyLedgerHeaderGross = "Gross"
    const val historyLedgerHeaderNet = "Net"
    const val historyLedgerHeaderDsop = "DSOP"
    const val historyLedgerHeaderTax = "Tax"
    const val dsopSimulatorTitle = "DSOP Simulator"
    const val dsopSimulatorMonthlySub = "Monthly Subscription"
    const val dsopSimulatorTaxWarning = "Tax Warning: Annual DSOP contributions above ₹5 Lakhs (₹41,666/mo) attract income tax on interest earned. Stay below ₹41,666/mo to keep gains 100% tax-free."
    const val dsopSimulatorTaxSafe = "Tax optimized: Annual contribution is below ₹5 Lakhs. All DSOP interest remains 100% tax-free under Section 10(11) of the Income Tax Act."
    const val dsopSimulator1Year = "1 Year Projection"
    const val dsopSimulator5Years = "5 Years Projection"
    const val dsopSimulator10Years = "10 Years Projection"
    const val dsopSimulator15Years = "15 Years Projection"
    const val dsopProjectionSubtext1Year = "Opening DSOP balance + 1 year tax-free compounding"
    const val dsopProjectionSubtext5Years = "Opening DSOP balance + 5 years tax-free compounding"
    const val dsopProjectionSubtext10Years = "Opening DSOP balance + 10 years tax-free compounding"
    const val dsopProjectionSubtext15Years = "Opening DSOP balance + 15 years tax-free compounding"
    const val dsopComparisonTitle = "15-Year Asset Wealth Comparison"
    const val dsopComparisonSubtitle = "Comparing DSOP against Indian saving instruments over 15 years"
    const val dsopAssetDsopLabel = "DSOP Fund (7.1% Tax-Free)"
    const val dsopAssetEquitiesLabel = "Equities / Nifty 50 (~12.0%)"
    const val dsopAssetGoldLabel = "Gold / Silver (~9.5%)"
    const val dsopAssetFdLabel = "Fixed Deposit (~7.0% Taxable)"
    const val dsopAssetTaxFreeNote = "🛡️ DSOP interest up to ₹5L/yr is 100% Tax-Free under Sec 10(11). Equities & Gold attract 12.5% LTCG tax, while FDs are fully taxable at your income slab."
    const val insightsEmptyState = "Please import or select a payslip to unlock financial insights."
    const val legendNetTakeHome = "Net Take-Home"
    const val legendDsop = "Provident Fund (DSOP)"
    const val legendTax = "Taxes & Cess"
    const val legendOtherDeductions = "Other Deductions"
    const val legendGrossPay = "Gross Pay"
    const val legendNetRemittance = "Net Remittance"
    const val chartNoDataAvailable = "No data available"
    const val dashboardEmptyStateTitle = "No Payslips Imported"
    const val dashboardEmptyStateDesc = "Import your monthly payslips to unlock digital replicas, historical tracking, financial insights, and tax audits."
    const val dashboardEmptyStateLabel = "Tap the + button below to get started"
    const val dashboardEmptyStateDescSandbox = "Import your PDF payslips or seed simulated data from the import screen to view financial analytics."
    const val ledgerMismatchIconDesc = "Ledger mismatch"
    const val ledgerCreditMismatchPrefix = "Credits over by ₹"
    const val ledgerDebitMismatchPrefix = "Debits over by ₹"
    const val correctionDialogEditOption = "Edit Value"
    const val correctionDialogDeleteOption = "Delete Entry"
    const val correctionDialogAddEarningTitle = "Add Earning Entry"
    const val correctionDialogAddDeductionTitle = "Add Deduction Entry"
    const val correctionDialogCodeHeadLabel = "Code Head (Abbreviation)"
    const val correctionDialogCustomCodeHeadPlaceholder = "e.g., A/o DA, Misc"
    const val correctionDialogAmountLabel = "Amount (₹)"
    const val correctionDialogOriginalAmountLabel = "Original Parsed Amount: ₹"
    const val correctionDialogSaveDraft = "Add to Session"
    const val correctionDialogDeleteWarning = "This entry will be marked as deleted in your local replica session."
    const val correctionSessionActivePrefix = "Draft Session Active"
    const val correctionSessionDiscard = "Discard"
    const val correctionSessionApply = "Apply"

    // Anti-Sideload & Security
    const val sideloadBlockedTitle = "Security Violation: Untrusted Installation"
    const val sideloadBlockedMessage = "This application build was installed from an unverified third-party source or has been modified. To protect your financial data and security, please install the official application from the Google Play Store."
    const val sideloadGetOfficialAppButton = "Get Official App"
    const val playStoreUrl = "https://play.google.com/store/apps/details?id=com.payslipmax.pdfparser"
}
